### ISSUE TITLE
Missing quoteidentifier for database

### ISSUE THREAD

**Issue by mokraemer** [BenMorel/mysql-replication-check#2]
e.g. if the databasename contains "-"

the statement
`$statement = $master->query("SHOW FULL TABLES FROM $database WHERE Table_Type != 'VIEW'");`

must be changed to
`$statement = $master->query("SHOW FULL TABLES FROM ".quoteIdentifier($database)." WHERE Table_Type != 'VIEW'");`

**Comment by mokraemer** [comment]
[bug2.txt](https://github.com/BenMorel/mysql-replication-check/files/7684247/bug2.txt)

**Comment by BenMorel** [comment]
Thank you! Fixed in fe2dcabd78a67442bd2cebc95125dbafa9a9fa69.
