### ISSUE TITLE
PDO exception: SQLSTATE[3D000]: Invalid catalog name: 1046 No database selected

### ISSUE THREAD

**Issue by mokraemer** [BenMorel/mysql-replication-check#3]
quoteIdentifier does not respect databasename.

e.g. `'LOCK TABLES ' . quoteIdentifier($table) . ' READ'`
results in
LOCK TABLES \`database.table\` READ
and NOT
LOCK TABLES \`database\`.\`table\` READ

I wonder this code ever worked...

**Comment by mokraemer** [comment]
suggest changing quoteIdentifier to:

function quoteIdentifier($name) {
 return '\`' . strtr($name,['\`'=>'\`\`','.'=>'\`.\`']) . '\`';
}

**Comment by mokraemer** [comment]
[bug3.txt](https://github.com/BenMorel/mysql-replication-check/files/7684262/bug3.txt)

**Comment by BenMorel** [comment]
Fixed in b4b715282ac6d7ba42b0b579003fe4565f3ac10b.
