### ISSUE TITLE
Summarize all failed tables

### ISSUE THREAD

**Issue by mokraemer** [BenMorel/mysql-replication-check#6]
Currently all tables are processed and the result is written immedeately, but at the end only the error count is written. Here it is desired to have the failed tables shown again.

**Comment by mokraemer** [comment]
[bug6.txt](https://github.com/BenMorel/mysql-replication-check/files/7684327/bug6.txt)

**Comment by mokraemer** [comment]
[bug6.txt](https://github.com/BenMorel/mysql-replication-check/files/7684348/bug6.txt)

**Comment by mokraemer** [comment]
[bug6.txt](https://github.com/BenMorel/mysql-replication-check/files/7684825/bug6.txt)

**Comment by BenMorel** [comment]
Fixed in 5e52132dc209b4b7abff68a7379ae7888d7225e5.
