### ISSUE TITLE
Filters not working at all

### ISSUE THREAD

**Issue by alvaro-gh** [BenMorel/mysql-replication-check#7]
I'm testing this script using `--tables` and `--ignore-tables`. For some reason I always get `Nothing to do`. Using each of them cause the same. I don't know my way around PHP but the problem seems to be in the `tableMatchesFilter` function. Maybe for debugging purposes I was trying to use `m9_temp.*` as a filter for `--tables`.

**Comment by BenMorel** [comment]
Hi, sorry for the (very) late reply. Which version are you using? IIRC, version `0.1.2` was flawed and could do something like this.

**Comment by BenMorel** [comment]
Closing due to lack of feedback.
